# Generated by Django 3.2.3 on 2021-05-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollanswer',
            old_name='users',
            new_name='user_votes',
        ),
    ]
