# Generated by Django 3.2.3 on 2021-05-28 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_rename_users_pollanswer_user_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='user_votes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='polls',
            field=models.ManyToManyField(to='polls.Poll'),
        ),
    ]
