# Generated by Django 3.2.3 on 2021-05-28 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_auto_20210528_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='user_votes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='polls',
            field=models.ManyToManyField(blank=True, to='polls.Poll'),
        ),
    ]
