# Generated by Django 3.2.3 on 2021-05-25 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0003_pollanswer_tag_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollanswer',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
