# Generated by Django 3.2.3 on 2021-05-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_pollanswer_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
