# Generated by Django 3.2.3 on 2021-05-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.IntegerField(max_length=15),
        ),
    ]
