# Generated by Django 3.2.3 on 2021-05-26 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0006_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='polls',
            field=models.ManyToManyField(blank=True, null=True, to='entities.Poll'),
        ),
    ]
